/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.EnderFire.PALogisticsDesk.Views;

import com.EnderFire.PALogisticsDesk.Views.Admin.TableViewForm;
import com.EnderFire.PALogisticsDesk.Models.*;

/**
 *
 * @author Oscar2
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public AdminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ClienteBut = new javax.swing.JButton();
        ProveedorBut = new javax.swing.JButton();
        OrdenCompraBut = new javax.swing.JButton();
        CentroDistribucionBut = new javax.swing.JButton();
        InformacionContactoBut = new javax.swing.JButton();
        RendimientosBut = new javax.swing.JButton();
        ContratoBut = new javax.swing.JButton();
        AlmacenBut = new javax.swing.JButton();
        PreferenciaBut = new javax.swing.JButton();
        MercanciaBut = new javax.swing.JButton();
        TransportitstaBut = new javax.swing.JButton();
        RutaBut = new javax.swing.JButton();
        PedidoBut = new javax.swing.JButton();
        UbicacionBut = new javax.swing.JButton();
        ReturnBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Admin Menu");

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(4, 4, 5, 5));

        ClienteBut.setText("Clientes");
        ClienteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteButActionPerformed(evt);
            }
        });
        jPanel1.add(ClienteBut);

        ProveedorBut.setText("Proveedores");
        ProveedorBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorButActionPerformed(evt);
            }
        });
        jPanel1.add(ProveedorBut);

        OrdenCompraBut.setText("Ordenes de compra");
        OrdenCompraBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenCompraButActionPerformed(evt);
            }
        });
        jPanel1.add(OrdenCompraBut);

        CentroDistribucionBut.setText("Centros de Distribucion");
        CentroDistribucionBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CentroDistribucionButActionPerformed(evt);
            }
        });
        jPanel1.add(CentroDistribucionBut);

        InformacionContactoBut.setText("Informacion de Contacto");
        InformacionContactoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionContactoButActionPerformed(evt);
            }
        });
        jPanel1.add(InformacionContactoBut);

        RendimientosBut.setText("Rendimientos");
        RendimientosBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RendimientosButActionPerformed(evt);
            }
        });
        jPanel1.add(RendimientosBut);

        ContratoBut.setText("Contratos");
        ContratoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratoButActionPerformed(evt);
            }
        });
        jPanel1.add(ContratoBut);

        AlmacenBut.setText("Almacenes");
        AlmacenBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmacenButActionPerformed(evt);
            }
        });
        jPanel1.add(AlmacenBut);

        PreferenciaBut.setText("Preferencias");
        PreferenciaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreferenciaButActionPerformed(evt);
            }
        });
        jPanel1.add(PreferenciaBut);

        MercanciaBut.setText("Mercancias");
        MercanciaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercanciaButActionPerformed(evt);
            }
        });
        jPanel1.add(MercanciaBut);

        TransportitstaBut.setText("Transportistas");
        TransportitstaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransportitstaButActionPerformed(evt);
            }
        });
        jPanel1.add(TransportitstaBut);

        RutaBut.setText("Rutas");
        RutaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaButActionPerformed(evt);
            }
        });
        jPanel1.add(RutaBut);

        PedidoBut.setText("Pedidos");
        PedidoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoButActionPerformed(evt);
            }
        });
        jPanel1.add(PedidoBut);

        UbicacionBut.setText("Ubicaciones");
        UbicacionBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbicacionButActionPerformed(evt);
            }
        });
        jPanel1.add(UbicacionBut);

        ReturnBut.setText("Retroceder");
        ReturnBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReturnBut, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReturnBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RutaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaButActionPerformed
        new TableViewForm(Ruta.class).setVisible(true);
    }//GEN-LAST:event_RutaButActionPerformed

    private void ClienteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteButActionPerformed
        new TableViewForm(Cliente.class).setVisible(true);
    }//GEN-LAST:event_ClienteButActionPerformed

    private void ProveedorButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorButActionPerformed
        new TableViewForm(Proveedor.class).setVisible(true);
    }//GEN-LAST:event_ProveedorButActionPerformed

    private void OrdenCompraButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenCompraButActionPerformed
        new TableViewForm(OrdenCompra.class).setVisible(true);
    }//GEN-LAST:event_OrdenCompraButActionPerformed

    private void CentroDistribucionButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CentroDistribucionButActionPerformed
        new TableViewForm(CentroDistribucion.class).setVisible(true);
    }//GEN-LAST:event_CentroDistribucionButActionPerformed

    private void InformacionContactoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionContactoButActionPerformed
        new TableViewForm(InformacionContacto.class).setVisible(true);
    }//GEN-LAST:event_InformacionContactoButActionPerformed

    private void RendimientosButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RendimientosButActionPerformed
        new TableViewForm(RendimientoProveedor.class).setVisible(true);
    }//GEN-LAST:event_RendimientosButActionPerformed

    private void ContratoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratoButActionPerformed
        new TableViewForm(Contrato.class).setVisible(true);
    }//GEN-LAST:event_ContratoButActionPerformed

    private void AlmacenButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmacenButActionPerformed
        new TableViewForm(Almacen.class).setVisible(true);
    }//GEN-LAST:event_AlmacenButActionPerformed

    private void PreferenciaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreferenciaButActionPerformed
        new TableViewForm(Preferencia.class).setVisible(true);
    }//GEN-LAST:event_PreferenciaButActionPerformed

    private void MercanciaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercanciaButActionPerformed
        new TableViewForm(Mercancia.class).setVisible(true);
    }//GEN-LAST:event_MercanciaButActionPerformed

    private void TransportitstaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransportitstaButActionPerformed
        new TableViewForm(Transportista.class).setVisible(true);
    }//GEN-LAST:event_TransportitstaButActionPerformed

    private void PedidoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoButActionPerformed
        new TableViewForm(Pedido.class).setVisible(true);
    }//GEN-LAST:event_PedidoButActionPerformed

    private void UbicacionButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbicacionButActionPerformed
        new TableViewForm(Ubicacion.class).setVisible(true);
    }//GEN-LAST:event_UbicacionButActionPerformed

    private void ReturnButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButActionPerformed
        new UserSelectForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_ReturnButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlmacenBut;
    private javax.swing.JButton CentroDistribucionBut;
    private javax.swing.JButton ClienteBut;
    private javax.swing.JButton ContratoBut;
    private javax.swing.JButton InformacionContactoBut;
    private javax.swing.JButton MercanciaBut;
    private javax.swing.JButton OrdenCompraBut;
    private javax.swing.JButton PedidoBut;
    private javax.swing.JButton PreferenciaBut;
    private javax.swing.JButton ProveedorBut;
    private javax.swing.JButton RendimientosBut;
    private javax.swing.JButton ReturnBut;
    private javax.swing.JButton RutaBut;
    private javax.swing.JButton TransportitstaBut;
    private javax.swing.JButton UbicacionBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
